const mongoose = require("mongoose");

// ab mujhe banana he product ka schema ki mujhe kyakya chahiye product ke andar like product name and uska description
const productSchema = new mongoose.Schema({
    name: {
        type: String,
        required: [true, "Please Enter product Name"],
        trim: true
    },

    description: {
        type: String,
        required: [true, "Please Enter product Description"]
    },

    price: {
        type: Number,
        required: [true, "Please Enter product Price"]
    },

    rating: {
        type: Number,
        default: 0
    },

    //ham apni image host karne ke use karenge cloud mery because jab bhi ham image upload karenge hame ek public id or ek url milta he  or arrray me rakha iski ek wajah beacuse images hogi array of objects 
    images: [
        {
            public_id: {
                type: String,
                required: true
            },
            url: {
                type: String,
                required: true
            }
        }
    ],

    category: {
        type: String,
        required: [true, "Please Enter product Category"]

    },

    Stock: {
        type: Number,
        required: [true, "Please Enter Product Stock"],
        maxLength: [4, "Stock cannot exceed 4 characters"],
        default: 1
    },

    numOfReviews: {
        type: Number,
        default: 0
    },


    // array liya kyuki reveiew ek product ke bohot sare log de sakte he

    reviews: [
        {

            name: {
                type: String,
                required: true,
            },
            rating: {
                type: Number,
                required: true
            },
            Comment: {
                type: String,
                requied: true,
                maxlength: [280, "comment can not exceed 280 characters"]
            },

        },
    ],

    user: {
        type: mongoose.Schema.ObjectId, // This field will store the unique identifier (ObjectId) of a user
        ref: "User", // This indicates that the ObjectId refers to the "User" model in the database
        required: true, // It is mandatory for each product to have a reference to a user
    },


    /*  // Explanation:
  
  user Field:
  
  This is a field in a MongoDB document (in this case, a product document) that will store information about the user who created the product.
  type: mongoose.Schema.ObjectId:
  
  The type property specifies the type of data that will be stored in this field. In this case, it's a MongoDB ObjectId, which is a unique identifier automatically generated by MongoDB for each document.
  ref: "User":
  
  The ref property specifies that the ObjectId stored in this field refers to a document in the "User" model. It establishes a relationship between the "Product" model and the "User" model.
  required: true:
  
  This property indicates that a value for the user field is required for every product document. In other words, each product must be associated with a user.
      
  */

    createAt: {
        type: Date,
        default: Date.now
    }

});

module.exports = mongoose.model("Product", productSchema);   // mongoose ke model ko export kare he